# Generated by Django 2.2.1 on 2019-05-05 10:08

from django.db import migrations


def create_default_organization(apps, _):
    Organization = apps.get_model('alerts', 'Organization')
    # TODO: get name from settings
    Organization.objects.create(name='Main')


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_organization)
    ]
