# Generated by Django 2.2.1 on 2019-05-19 15:34

import alert_control_center.utils.url
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_team_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1048576)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncomingWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(default=alert_control_center.utils.url.short_url_token, max_length=50, unique=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.IncomingChannel')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.AlertVendor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='incomingwebhook',
            constraint=models.UniqueConstraint(fields=('url',), name='uq_url'),
        ),
    ]
