# Generated by Django 2.2.1 on 2019-05-19 15:30

from django.db import migrations


def add_vendor(apps, _):
    AlertVendor = apps.get_model('alerts', 'AlertVendor')
    # TODO: get name from settings
    AlertVendor.objects.create(name='New Relic')


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20190519_1534'),
    ]

    operations = [
        migrations.RunPython(add_vendor)
    ]
