# Generated by Django 2.2.1 on 2019-05-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20190519_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingWebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.TextField()),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='alerts.IncomingWebhook')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
